// Generated by gencpp from file lla2enu/distance.msg
// DO NOT EDIT!


#ifndef LLA2ENU_MESSAGE_DISTANCE_H
#define LLA2ENU_MESSAGE_DISTANCE_H

#include <ros/service_traits.h>


#include <lla2enu/distanceRequest.h>
#include <lla2enu/distanceResponse.h>


namespace lla2enu
{

struct distance
{

typedef distanceRequest Request;
typedef distanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct distance
} // namespace lla2enu


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lla2enu::distance > {
  static const char* value()
  {
    return "7cbb544062a87ec579943aaefdb83692";
  }

  static const char* value(const ::lla2enu::distance&) { return value(); }
};

template<>
struct DataType< ::lla2enu::distance > {
  static const char* value()
  {
    return "lla2enu/distance";
  }

  static const char* value(const ::lla2enu::distance&) { return value(); }
};


// service_traits::MD5Sum< ::lla2enu::distanceRequest> should match
// service_traits::MD5Sum< ::lla2enu::distance >
template<>
struct MD5Sum< ::lla2enu::distanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lla2enu::distance >::value();
  }
  static const char* value(const ::lla2enu::distanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lla2enu::distanceRequest> should match
// service_traits::DataType< ::lla2enu::distance >
template<>
struct DataType< ::lla2enu::distanceRequest>
{
  static const char* value()
  {
    return DataType< ::lla2enu::distance >::value();
  }
  static const char* value(const ::lla2enu::distanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lla2enu::distanceResponse> should match
// service_traits::MD5Sum< ::lla2enu::distance >
template<>
struct MD5Sum< ::lla2enu::distanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lla2enu::distance >::value();
  }
  static const char* value(const ::lla2enu::distanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lla2enu::distanceResponse> should match
// service_traits::DataType< ::lla2enu::distance >
template<>
struct DataType< ::lla2enu::distanceResponse>
{
  static const char* value()
  {
    return DataType< ::lla2enu::distance >::value();
  }
  static const char* value(const ::lla2enu::distanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LLA2ENU_MESSAGE_DISTANCE_H
